In [2]:
import pandas as pd 

#Import csv files generated by each group member
file_2015 = "2015_Top30zipcodes.csv"
file_2016 = "2016_Top30zipcodes.csv"
file_2017 = "2017_Top30codes"
file_2018 = "2018_Top30zipcodes.csv"

#read each csv file
df1 = pd.read_csv(file_2015)
df2 = pd.read_csv(file_2016)
df3 = pd.read_csv(file_2017)
df4 = pd.read_csv(file_2018)

#concatenate all of the csv files into one csv file
merge = pd.concat([df1["Zip Code"],df2["Zip Code"],df3["Zip Code"],df4["zipcode"]],ignore_index=True)
#merge and convert to dataframe
convert = merge.to_frame()

#create final df and con
final_df = convert.rename(index=str, columns={0: "Zip Codes"})
final_df.to_csv("consolidated.csv", sep=",")
zipcodes = final_df.groupby(["Zip Codes"])["Zip Codes"].count()
zipcodes

Zip Codes
10002    4
10003    4
10009    4
10011    4
10012    4
10013    1
10014    4
10016    4
10019    4
10023    4
10024    3
10025    4
10027    4
10029    4
10031    4
10032    1
10036    4
10128    1
11201    3
11205    4
11206    4
11211    4
11213    1
11215    4
11216    4
11217    4
11221    4
11222    4
11225    3
11226    4
11233    3
11237    4
11238    4
11249    4
Name: Zip Codes, dtype: int64

In [3]:
#consolidated3.csv is a csv containing the ouput from the previous code with 'Borough' and 'Neighborhood information' (See https://www.health.ny.gov/statistics/cancer/registry/appendix/neighborhoods.htm) that was externally added
consoldf = pd.read_csv("consolidated3.csv")
consoldf

    Count  Zip Codes    Borough                   Neighborhood
0       4      11206   Brooklyn      Bushwick and Williamsburg
1       4      11221   Brooklyn      Bushwick and Williamsburg
2       4      11237   Brooklyn      Bushwick and Williamsburg
3       4      11216   Brooklyn               Central Brooklyn
4       3      11233   Brooklyn               Central Brooklyn
5       4      11238   Brooklyn               Central Brooklyn
6       4      10027  Manhattan                 Central Harlem
7       4      10011  Manhattan            Chelsea and Clinton
8       4      10019  Manhattan            Chelsea and Clinton
9       4      10036  Manhattan            Chelsea and Clinton
10      4      10029  Manhattan                    East Harlem
11      3      11225   Brooklyn                       Flatbush
12      4      11226   Brooklyn                       Flatbush
13      4      10016  Manhattan  Gramercy Park and Murray Hill
14      4      11211   Brooklyn                     Greenpoint
15      4      11222   Brooklyn                     Greenpoint
16      4      10012  Manhattan     Greenwich Village and Soho
17      4      10014  Manhattan     Greenwich Village and Soho
18      4      10031  Manhattan  Inwood and Washington Heights
19      4      10002  Manhattan                Lower East Side
20      4      10003  Manhattan                Lower East Side
21      4      10009  Manhattan                Lower East Side
22      3      11201   Brooklyn             Northwest Brooklyn
23      4      11205   Brooklyn             Northwest Brooklyn
24      4      11215   Brooklyn             Northwest Brooklyn
25      4      11217   Brooklyn             Northwest Brooklyn
26      4      10023  Manhattan                Upper West Side
27      3      10024  Manhattan                Upper West Side
28      4      10025  Manhattan                Upper West Side