In [98]:
#US Census API 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

api_key = "9c43c55c9067920bded793b5c4d99ae0aba10281"

c = Census(api_key, year=2017)
api_key

'9c43c55c9067920bded793b5c4d99ae0aba10281'

In [117]:
# Run Census Search to retrieve data on all zip codes (2013 ACS5 Census)
# See: https://github.com/CommerceDataService/census-wrapper for library documentation
# See: https://gist.github.com/afhaque/60558290d6efd892351c4b64e5c01e9b for labels
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E","B01002_001E"), {'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})

# Add in Poverty Rate (Poverty Count / Population)
census_pd["Poverty Rate"] = 100 * \
    census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

# Final DataFrame
census_pd = census_pd[["Zipcode", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Poverty Count", "Poverty Rate"]]

# Visualize
print(len(census_pd))
census_pd.head()

33120

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate
0,00601,17599.0,38.9,11757.0,7041.0,11282.0,64.105915
1,00602,39209.0,40.9,16190.0,8978.0,20428.0,52.100283
2,00603,50135.0,40.4,16645.0,10897.0,25176.0,50.216416
3,00606,6304.0,42.8,13387.0,5960.0,4092.0,64.911168
4,00610,27590.0,41.4,18741.0,9266.0,12553.0,45.498369

In [118]:
zips = ['10002','11201','11237','11233','11226',
 '11225','11222','11221','11217','11216','11215','11211','11206','11205','10036','10003',
 '10031','10029','10027','10025','10024','10023','10019','10016','10014','10012','10011',
 '10009','11238']

census_pd2 = census_pd[census_pd["Zipcode"].isin(zips)]
census_pd2

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate
2559,10002,77925.0,41.8,35449.0,30677.0,21214.0,27.223612
2560,10003,55035.0,32.6,104441.0,91141.0,3973.0,7.219042
2565,10009,60141.0,36.8,60521.0,47782.0,13822.0,22.982657
2567,10011,50711.0,39.8,123208.0,114218.0,5367.0,10.583503
2568,10012,24527.0,34.5,104561.0,85491.0,2631.0,10.726954
2570,10014,31794.0,36.8,127973.0,122098.0,2164.0,6.806316
2571,10016,51448.0,33.3,109250.0,88762.0,5325.0,10.350257
2574,10019,41592.0,39.6,99063.0,94797.0,4963.0,11.932583
2578,10023,61514.0,42.6,123951.0,114641.0,4862.0,7.903892
2579,10024,58512.0,43.1,126107.0,113584.0,4157.0,7.104526
2580,10025,94382.0,41.7,82352.0,68995.0,14370.0,15.225361
2582,10027,65365.0,30.7,45536.0,30256.0,17034.0,26.059818
2584,10029,80866.0,34.0,34015.0,27966.0,25037.0,30.961096
2586,10031,62382.0,34.8,44040.0,26417.0,14407.0,23.094803
2591,10036,26868.0,37.1,93707.0,77462.0,3868.0,14.396308
2825,11201,61907.0,35.0,116446.0,77491.0,8224.0,13.284443
2828,11205,45148.0,30.0,51574.0,28894.0,13155.0,29.137503
2829,11206,87767.0,29.2,34122.0,21148.0,31999.0,36.459034
2834,11211,101560.0,30.6,66113.0,39123.0,26815.0,26.403111
2838,11215,71015.0,35.5,116893.0,67148.0,5220.0,7.350560
2839,11216,57410.0,34.2,56025.0,34644.0,10801.0,18.813796
2840,11217,39687.0,35.1,99085.0,63967.0,5396.0,13.596392
2844,11221,84536.0,31.5,47170.0,24707.0,20853.0,24.667597
2845,11222,36845.0,35.0,78287.0,46592.0,4608.0,12.506446
2848,11225,59497.0,34.7,51926.0,30351.0,10932.0,18.374036
2849,11226,102585.0,34.1,48495.0,24798.0,19255.0,18.769801
2855,11233,74982.0,33.2,36009.0,22163.0,22477.0,29.976528
2859,11237,52319.0,30.3,51269.0,23115.0,15303.0,29.249412
2860,11238,55398.0,35.6,79013.0,49004.0,7284.0,13.148489

In [129]:
final30 = pd.read_csv('../Final_Trending_Zipcodes.csv')
final30 = final30.rename(columns={'Zip Codes': 'Zipcode'})

census_pd2['Zipcode']=census_pd2['Zipcode'].astype(int)

zipsmerged = pd.merge(census_pd2, final30, on="Zipcode", how="outer")

C:\Users\amand\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Borough,Neighborhood,Mean_2015,Median_2015,Mean_2016,Median_2016,Mean_2017,Median_2017,Mean_2018,Median_2018
0,10002,77925.0,41.8,35449.0,30677.0,21214.0,27.223612,Manhattan,Lower East Side,182.400477,150,168.815366,135,174.141667,129,171.128160,130.0
1,10003,55035.0,32.6,104441.0,91141.0,3973.0,7.219042,Manhattan,Lower East Side,220.328891,180,218.895993,169,220.491229,160,223.038827,169.0
2,10009,60141.0,36.8,60521.0,47782.0,13822.0,22.982657,Manhattan,Lower East Side,177.778549,150,165.071030,135,166.544186,135,170.691880,140.0
3,10011,50711.0,39.8,123208.0,114218.0,5367.0,10.583503,Manhattan,Chelsea and Clinton,242.854346,200,225.796277,199,225.691729,195,235.382632,190.0
4,10012,24527.0,34.5,104561.0,85491.0,2631.0,10.726954,Manhattan,Greenwich Village and Soho,255.219760,200,230.587597,190,224.176746,185,226.860020,185.0
5,10014,31794.0,36.8,127973.0,122098.0,2164.0,6.806316,Manhattan,Greenwich Village and Soho,252.500823,210,239.303179,200,244.652423,200,256.992884,200.0
6,10016,51448.0,33.3,109250.0,88762.0,5325.0,10.350257,Manhattan,Gramercy Park and Murray Hill,237.572914,185,214.245595,175,215.009782,170,219.999161,175.0
7,10019,41592.0,39.6,99063.0,94797.0,4963.0,11.932583,Manhattan,Chelsea and Clinton,229.525049,189,215.508512,175,215.059272,170,228.574660,180.0
8,10023,61514.0,42.6,123951.0,114641.0,4862.0,7.903892,Manhattan,Upper West Side,234.262821,190,223.957771,180,219.792201,182,219.262169,180.0
9,10024,58512.0,43.1,126107.0,113584.0,4157.0,7.104526,Manhattan,Upper West Side,205.716110,175,199.247779,165,0.000000,0,195.559349,159.0
10,10025,94382.0,41.7,82352.0,68995.0,14370.0,15.225361,Manhattan,Upper West Side,183.937928,145,158.431274,119,166.183255,110,166.790625,110.0
11,10027,65365.0,30.7,45536.0,30256.0,17034.0,26.059818,Manhattan,Central Harlem,128.709048,110,121.078350,100,135.229297,100,135.707509,100.0
12,10029,80866.0,34.0,34015.0,27966.0,25037.0,30.961096,Manhattan,East Harlem,126.461440,100,127.426550,100,129.885366,98,140.572068,95.0
13,10031,62382.0,34.8,44040.0,26417.0,14407.0,23.094803,Manhattan,Inwood and Washington Heights,104.395633,80,99.883374,75,95.558082,75,98.003266,75.0
14,10036,26868.0,37.1,93707.0,77462.0,3868.0,14.396308,Manhattan,Chelsea and Clinton,218.437125,175,212.077208,165,213.932102,168,215.999462,170.0
15,11201,61907.0,35.0,116446.0,77491.0,8224.0,13.284443,Brooklyn,Northwest Brooklyn,180.651959,155,166.963918,150,174.439658,145,0.000000,0.0
16,11205,45148.0,30.0,51574.0,28894.0,13155.0,29.137503,Brooklyn,Northwest Brooklyn,165.375414,115,154.145494,100,140.440341,99,140.647674,99.0
17,11206,87767.0,29.2,34122.0,21148.0,31999.0,36.459034,Brooklyn,Bushwick and Williamsburg,102.391970,80,94.994238,75,94.821426,75,96.825835,75.0
18,11211,101560.0,30.6,66113.0,39123.0,26815.0,26.403111,Brooklyn,Greenpoint,150.991682,129,143.768193,119,145.759296,113,146.840053,110.0
19,11215,71015.0,35.5,116893.0,67148.0,5220.0,7.350560,Brooklyn,Northwest Brooklyn,162.932613,139,150.024912,130,144.884473,129,147.097090,129.0
20,11216,57410.0,34.2,56025.0,34644.0,10801.0,18.813796,Brooklyn,Central Brooklyn,111.900207,90,110.022522,85,107.358035,85,110.636435,85.0
21,11217,39687.0,35.1,99085.0,63967.0,5396.0,13.596392,Brooklyn,Northwest Brooklyn,165.974973,140,164.352042,130,163.994170,130,162.188512,130.0
22,11221,84536.0,31.5,47170.0,24707.0,20853.0,24.667597,Brooklyn,Bushwick and Williamsburg,95.713076,75,89.587325,70,88.334267,69,87.629931,68.0
23,11222,36845.0,35.0,78287.0,46592.0,4608.0,12.506446,Brooklyn,Greenpoint,140.432536,120,128.623164,109,124.135188,100,135.671584,109.5
24,11225,59497.0,34.7,51926.0,30351.0,10932.0,18.374036,Brooklyn,Flatbush,0.000000,0,94.748649,80,95.294381,80,100.770975,83.0
25,11226,102585.0,34.1,48495.0,24798.0,19255.0,18.769801,Brooklyn,Flatbush,92.680582,75,84.754190,70,85.103783,69,85.033461,69.0
26,11233,74982.0,33.2,36009.0,22163.0,22477.0,29.976528,Brooklyn,Central Brooklyn,0.000000,0,105.371874,95,100.719001,80,99.172214,80.0
27,11237,52319.0,30.3,51269.0,23115.0,15303.0,29.249412,Brooklyn,Bushwick and Williamsburg,91.916442,75,86.114981,69,80.728763,65,79.219594,65.0
28,11238,55398.0,35.6,79013.0,49004.0,7284.0,13.148489,Brooklyn,Central Brooklyn,144.082211,120,138.259867,106,135.210127,100,137.844509,105.0

In [130]:
zipsmerged.to_csv('Census_AirBnB.csv', index=False)

In [102]:
zipcode_30 = pd.read_csv("../Final_Trending_Zipcodes.csv")
zipcode_30

,Zip Codes,Borough,Neighborhood,Mean_2015,Median_2015,Mean_2016,Median_2016,Mean_2017,Median_2017,Mean_2018,Median_2018
0,11206,Brooklyn,Bushwick and Williamsburg,102.391970,80,94.994238,75,94.821426,75,96.825835,75.0
1,11221,Brooklyn,Bushwick and Williamsburg,95.713076,75,89.587325,70,88.334267,69,87.629931,68.0
2,11237,Brooklyn,Bushwick and Williamsburg,91.916442,75,86.114981,69,80.728763,65,79.219594,65.0
3,11216,Brooklyn,Central Brooklyn,111.900207,90,110.022522,85,107.358035,85,110.636435,85.0
4,11238,Brooklyn,Central Brooklyn,144.082211,120,138.259867,106,135.210127,100,137.844509,105.0
5,10027,Manhattan,Central Harlem,128.709048,110,121.078350,100,135.229297,100,135.707509,100.0
6,10011,Manhattan,Chelsea and Clinton,242.854346,200,225.796277,199,225.691729,195,235.382632,190.0
7,10019,Manhattan,Chelsea and Clinton,229.525049,189,215.508512,175,215.059272,170,228.574660,180.0
8,10036,Manhattan,Chelsea and Clinton,218.437125,175,212.077208,165,213.932102,168,215.999462,170.0
9,10029,Manhattan,East Harlem,126.461440,100,127.426550,100,129.885366,98,140.572068,95.0
10,11226,Brooklyn,Flatbush,92.680582,75,84.754190,70,85.103783,69,85.033461,69.0
11,10016,Manhattan,Gramercy Park and Murray Hill,237.572914,185,214.245595,175,215.009782,170,219.999161,175.0
12,11211,Brooklyn,Greenpoint,150.991682,129,143.768193,119,145.759296,113,146.840053,110.0
13,11222,Brooklyn,Greenpoint,140.432536,120,128.623164,109,124.135188,100,135.671584,109.5
14,10012,Manhattan,Greenwich Village and Soho,255.219760,200,230.587597,190,224.176746,185,226.860020,185.0
15,10014,Manhattan,Greenwich Village and Soho,252.500823,210,239.303179,200,244.652423,200,256.992884,200.0
16,10031,Manhattan,Inwood and Washington Heights,104.395633,80,99.883374,75,95.558082,75,98.003266,75.0
17,10002,Manhattan,Lower East Side,182.400477,150,168.815366,135,174.141667,129,171.128160,130.0
18,10003,Manhattan,Lower East Side,220.328891,180,218.895993,169,220.491229,160,223.038827,169.0
19,10009,Manhattan,Lower East Side,177.778549,150,165.071030,135,166.544186,135,170.691880,140.0
20,11205,Brooklyn,Northwest Brooklyn,165.375414,115,154.145494,100,140.440341,99,140.647674,99.0
21,11215,Brooklyn,Northwest Brooklyn,162.932613,139,150.024912,130,144.884473,129,147.097090,129.0
22,11217,Brooklyn,Northwest Brooklyn,165.974973,140,164.352042,130,163.994170,130,162.188512,130.0
23,10023,Manhattan,Upper West Side,234.262821,190,223.957771,180,219.792201,182,219.262169,180.0
24,10025,Manhattan,Upper West Side,183.937928,145,158.431274,119,166.183255,110,166.790625,110.0
25,11233,Brooklyn,Central Brooklyn,0.000000,0,105.371874,95,100.719001,80,99.172214,80.0
26,11225,Brooklyn,Flatbush,0.000000,0,94.748649,80,95.294381,80,100.770975,83.0
27,11201,Brooklyn,Northwest Brooklyn,180.651959,155,166.963918,150,174.439658,145,0.000000,0.0
28,10024,Manhattan,Upper West Side,205.716110,175,199.247779,165,0.000000,0,195.559349,159.0

In [103]:
zipcode_30['Zip Codes']=zipcode_30['Zip Codes'].astype(str)
zipcode_30.dtypes

Zip Codes        object
Borough          object
Neighborhood     object
Mean_2015       float64
Median_2015       int64
Mean_2016       float64
Median_2016       int64
Mean_2017       float64
Median_2017       int64
Mean_2018       float64
Median_2018     float64
dtype: object

In [104]:
zips = zipcode_30.groupby('Zip Codes').count()
zips = zips.sort_values('Borough', ascending=False)

zip_list = list(zips.index.values)
zipcodes = zip_list[0:30]
zipcodes

['10002',
 '11201',
 '11237',
 '11233',
 '11226',
 '11225',
 '11222',
 '11221',
 '11217',
 '11216',
 '11215',
 '11211',
 '11206',
 '11205',
 '10036',
 '10003',
 '10031',
 '10029',
 '10027',
 '10025',
 '10024',
 '10023',
 '10019',
 '10016',
 '10014',
 '10012',
 '10011',
 '10009',
 '11238']